name: 'ResX Translation and Combination'
description: 'A Github action that searches for default, automatically translated, and manually overriden ResX files, automatically translates missing texts, and combines them to directly usable ResX files.'
branding:
  icon: file-plus
  color: purple
inputs:
  dir:
    description: 'The root directory to work from. Example, "path/to/code".'
    required: false
    default: '.'
  auth:
    description: 'Auth key for your DeepL API access.'
    required: true
  excludes-regex:
    description: 'Regex for names of default ResX files in order to decide whether to exclude file from processing.'
    required: false
    default: ''
  data-copies-regex:
    description: 'Regex for names of default ResX files whose data should be copied instead of translated.'
    required: false
    default: ''
  filter-keys-with-overrides:
    description: 'If set the default keys are filtered by the super set of override keys per ResX file family.'
    required: false
    default: 'false'
outputs:
  summary-title:
    description: 'The title of the commit for the pull request.'
  summary-details:
    description: 'The summary details of the commit for the pull request.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '-d'
  - ${{ inputs.dir }}
  - '-a'
  - ${{ inputs.auth }}
  - '-e'
  - ${{ inputs.excludes-regex }}
  - '-c'
  - ${{ inputs.data-copies-regex }}
  - '-f'
  - ${{ inputs.filter-keys-with-overrides }}
